name: Auto Comment
on:
  pull_request:
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          pullRequestClosed: >
            👋 @{{ author }} This PR is closed.

          pullRequestMerged: >
            👋 @{{ author }} This PR is merged.
